# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 172.17.0.1:9093

rule_files:
  - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'hk-pub-nginx-61'
    static_configs:
    - targets: ['172.31.24.61:9100']
      labels:
        ip: '172.31.24.61'

  - job_name: 'hk-pub-redis-236'
    static_configs:
    - targets: ['172.31.27.236:9100']
      labels:
        ip: '172.31.27.236'
